### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/connector-accountedge#9]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] hr_expense_line_sequence
- [ ] account_tax_accountedge
- [ ] hr_expense_line_supplier_tax
- [ ] hr_expense_accountedge
- [ ] hr_expense_line_account
- [ ] account_account_halftax
- [ ] hr_employee_accountedge
